In [ ]:
import numpy as np

In [4]:
a=np.array([a for a in range(1,500,3)],dtype="uint8")

In [5]:
print(a)

[  1   4   7  10  13  16  19  22  25  28  31  34  37  40  43  46  49  52
  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97 100 103 106
 109 112 115 118 121 124 127 130 133 136 139 142 145 148 151 154 157 160
 163 166 169 172 175 178 181 184 187 190 193 196 199 202 205 208 211 214
 217 220 223 226 229 232 235 238 241 244 247 250 253   0   3   6   9  12
  15  18  21  24  27  30  33  36  39  42  45  48  51  54  57  60  63  66
  69  72  75  78  81  84  87  90  93  96  99 102 105 108 111 114 117 120
 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174
 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228
 231 234 237 240 243]


In [10]:
a.ndim

1

In [11]:
a.shape

(167,)

In [12]:
a.dtype

dtype('int16')

In [13]:
a.size

167

In [14]:
a.nbytes

334

In [20]:
p=np.array([[1,2,3,4,5,6],[8,7,9,10,11,12]])

In [22]:
p[1,-2]

11

In [24]:
p[:,2]#column 3 all

array([3, 9])

In [25]:
p[1,:] #row 2 all

array([ 8,  7,  9, 10, 11, 12])

In [28]:
p[1,1:6:2] #row 2 all hop 2 elements

array([ 7, 10, 12])

In [29]:
p[:,1]=23,24 #changeing all in colum 2

print(p)

In [55]:
p[1,5::-1]=[a for a in range(21,27)]

In [56]:
print(p)

[[ 1 23 42  4  5  6]
 [26 25 24 23 22 21]]


In [2]:
b=np.array([[1,1,2],[1,1,4],[1,2,3],[4,5,6]])

In [62]:
c=[a for a in b]

In [63]:
c

[array([1, 1, 2]), array([1, 1, 4]), array([1, 2, 3]), array([4, 5, 6])]

In [67]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [69]:
np.ones((2,3,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [70]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [3]:
np.full_like(b,[2,3,4])

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [78]:
np.random.rand(5,6)

array([[0.88024775, 0.24301238, 0.17838019, 0.64406691, 0.29321894,
        0.62336065],
       [0.28457334, 0.65521566, 0.15028011, 0.1310055 , 0.22268442,
        0.51182726],
       [0.27406921, 0.48593151, 0.63127841, 0.28624367, 0.95138017,
        0.90371644],
       [0.28947431, 0.17112823, 0.98660314, 0.54898429, 0.38559827,
        0.46776257],
       [0.39331107, 0.0488405 , 0.52271436, 0.94082253, 0.17577888,
        0.57675985]])

In [85]:
np.random.randint(3,67,size=(2,4))

array([[63, 57, 22, 29],
       [60, 40, 43, 15]])

In [86]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
r=np.repeat(b,3,axis=1)

In [88]:
print(r)

[[1 1 1 1 1 1 2 2 2]
 [1 1 1 1 1 1 4 4 4]
 [1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]


In [89]:
r=np.repeat(b,3,axis=0)

In [90]:
print(r)

[[1 1 2]
 [1 1 2]
 [1 1 2]
 [1 1 4]
 [1 1 4]
 [1 1 4]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [101]:
n=np.ones((5,5))

In [108]:
n[1:4,1:4]=0 #the second 4 is not counted
#so less then that is 3

In [109]:
n[2,2]=9

In [110]:
print(n)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [112]:
#copyieng
# array
a=np.identity(3)

In [113]:
gd=a.copy()

In [114]:
gd

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [115]:
gd[1,1]=2121

In [116]:
gd

array([[1.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 2.121e+03, 0.000e+00],
       [0.000e+00, 0.000e+00, 1.000e+00]])

In [117]:
gd.dtype

dtype('float64')

In [125]:
bf=np.array([a for a in range(50)])

In [129]:
bf.min()

0

In [130]:
a=np.array([1,2,3])

In [131]:
b=np.array([4,5,6])

In [137]:
a+b

array([5, 7, 9])

In [138]:
a-b

array([-3, -3, -3])

In [139]:
a%b

array([1, 2, 3])

In [140]:
a/b

array([0.25, 0.4 , 0.5 ])

In [143]:
a+5

array([6, 7, 8])

In [144]:
a

array([1, 2, 3])

In [145]:
a+=5

In [146]:
a

array([6, 7, 8])

In [147]:
np.sin(a)

array([-0.2794155 ,  0.6569866 ,  0.98935825])

In [148]:
np.cos(a)

array([ 0.96017029,  0.75390225, -0.14550003])

In [149]:
np.tan(b)

array([ 1.15782128, -3.38051501, -0.29100619])

# Linear algbra

In [150]:
a=np.ones((3,3))

In [151]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
b=np.full((3,3),21)

In [153]:
b

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [155]:
a*b

array([[21., 21., 21.],
       [21., 21., 21.],
       [21., 21., 21.]])

In [156]:
np.matmul(a,b)

array([[63., 63., 63.],
       [63., 63., 63.],
       [63., 63., 63.]])

In [163]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [167]:
np.min(b,axis=1)# in axis 1 in column and 0 is row wise

array([21, 21, 21])

In [169]:
np.sum(b)

189

In [170]:
be=np.array([[1,1,2],[1,1,4],[1,2,3],[4,5,6]])

In [171]:
be

array([[1, 1, 2],
       [1, 1, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [175]:
ae=be.reshape(2,6)# reshaping the be can be 
# converted to 3D but element must be same

In [176]:
ae

array([[1, 1, 2, 1, 1, 4],
       [1, 2, 3, 4, 5, 6]])

In [177]:
ad=ae.reshape(2,2,3)

In [178]:
ad

array([[[1, 1, 2],
        [1, 1, 4]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [187]:
fg=np.array(["a","b","c"])
gf=np.array(["a1","b1","c1"])

In [189]:
np.vstack([fg,gf,fg])

array([['a', 'b', 'c'],
       ['a1', 'b1', 'c1'],
       ['a', 'b', 'c']], dtype='<U2')

In [195]:
c=np.hstack([fg,gf])
for a in c:
    print(a)
# hroizontal stack not compatibel if size miss match

a
b
c
a1
b1
c1


In [204]:
filedata=np.genfromtxt('testtxt',delimiter='\n',dtype='<U2')
# for taking from file if it is a char then specify datatype
#  and if it have num they are print as it is
# while text is "nan"

In [205]:
filedata

array(['a', 'b', 'c', 'a1', 'b1', 'c1', '1', '3', '4', '6', '8', '9'],
      dtype='<U2')

In [206]:
ng=filedata.copy()

In [1]:
import numpy as np # the dimension must be same
# otherwise that will not be a C array but 
# C array with a object or python whole
# to see change delete one entry in below 2D array
c=np.array([[1,2,34,4],[1,2,4]])
c

array([list([1, 2, 34, 4]), list([1, 2, 4])], dtype=object)

In [2]:
c=np.array([[1,2,34,4],[1,2,4,4]]) 
# see the difference
c

array([[ 1,  2, 34,  4],
       [ 1,  2,  4,  4]])

In [3]:
x = np.array([(124,"-22"),(120,"32000")],dtype=[('a','i1'),('b','S5')])

In [4]:
x['b']

array([b'-22', b'32000'], dtype='|S5')

In [5]:
np.dtype([('hello',(np.int64,3)),('world',np.void,1)])

dtype([('hello', '<i8', (3,)), ('world', 'V1')])

In [6]:
d=np.genfromtxt('testtxt',delimiter=',',dtype='i1')

In [7]:
d

array([-1, -1, -1, -1, -1, -1,  1,  3,  4,  6,  8,  9], dtype=int8)

####Bool and advacne index

In [8]:
d >3

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True])

In [9]:
d[d>3]

array([4, 6, 8, 9], dtype=int8)

In [10]:
d[[1,3,8]]

array([-1, -1,  4], dtype=int8)

In [11]:
np.all(d>4)

False

In [12]:
np.any(d>4)

True

In [28]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [37]:
np.eye(4,5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [6]:
np.all()

TypeError: _all_dispatcher() missing 1 required positional argument: 'a'

In [9]:
"kartik is good".split("g",2)

['kartik is ', 'ood']

In [21]:
d={1:2,4:3}
v=d
# v=d.copy()
print(hex(id(v)))
print(hex(id(d)))
print(d)
del d
v.update({5:6})
# print()
print(hex(id(v)))
print(v)

0x7f6c5a6c4640
0x7f6c5a6c4640
{1: 2, 4: 3}
0x7f6c5a6c4640
{1: 2, 4: 3, 5: 6}


# testfor

In [55]:
d=np.ones((4,1))

In [56]:
d

array([[1.],
       [1.],
       [1.],
       [1.]])

In [57]:
d.transpose()

array([[1., 1., 1., 1.]])

In [21]:
import numpy as n

In [ ]:
a

# Eigen and norm

In [42]:
from numpy import linalg

In [75]:
a=n.arange(9)-3

In [76]:
# a.dtype="int32"

In [77]:
b=a.reshape(3,3)

In [78]:
b[2,:]-=4
b[:,2]+=3
b[0,2]=10
b

array([[-3, -2, 10],
       [ 0,  1,  5],
       [-1,  0,  4]])

In [84]:
n.linalg.norm(b,n.inf) # this is for the checking |g[:,y]| ka sum 

15.0

In [91]:
n.linalg.norm(b)

12.489995996796797