In [2]:
import numpy as np
ar=np.arange(0,20)

In [3]:
c=np.exp(ar)

In [4]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [6]:
ary=np.array([i for i in range(0,25)])

In [7]:
ary=ary.reshape(5,5)

In [8]:
ary

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
ary.sum(axis=0)

array([50, 55, 60, 65, 70])

In [10]:
ar**2
ar+=21
ar

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [66]:
v=np.array([range(i ,i+5) for i in (1,2,3,4,5) ],dtype=np.uint8)

In [67]:
v.ndim #dimensions

2

In [68]:
v.size # number of element

25

In [69]:
v.shape # shape

(5, 5)

In [70]:
v.nbytes #total bytes used

25

In [71]:
v.itemsize # item size

1

In [74]:
v

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]], dtype=uint8)