In [1]:
import numpy as n

In [5]:
a=n.abs([1,23,-3])

In [6]:
a.transpose() # not useable for 1D array

array([ 1, 23,  3])

In [7]:
a

array([ 1, 23,  3])

In [8]:
n.pi

3.141592653589793

In [15]:
a.reshape(3,1)

array([[ 1],
       [23],
       [ 3]])

In [27]:
d=n.arange(1000000)

In [28]:
d=d.reshape(1000,1000)

In [29]:
d.shape

(1000, 1000)

In [37]:
from numpy import linalg
import time

In [31]:
n.linalg.norm(d)

577349836.1768837

In [56]:
s=time.time()
n.linalg.norm(d[:,0],n.inf) # inf norm take more time to execute
f=time.time()
print(f-s)

0.0005497932434082031


In [59]:
f=n.array([[i,i+1,i+4] for i in range(1,9)])

In [89]:
f.shape

(8, 3)

* empty_like : Return an empty array with shape and type of input.
* ones_like : Return an array of ones with shape and type of input.
* zeros_like : Return an array of zeros with shape and type of input.
* full_like : Return a new array with shape of input filled with value.
* empty : Return a new uninitialized array.
* ones : Return a new array setting values to one.
* zeros : Return a new array setting values to zero.
* full : Return a new array of given shape filled with value.

In [86]:
n.empty_like(f,n.int8)

array([[ 1,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, 23],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0, -3, -1],
       [-1, -1, -1],
       [-1, -1, -1]], dtype=int8)

In [98]:
n.ones_like(f,n.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [95]:
n.zeros_like(f,n.int8,shape=24)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int8)

In [99]:
n.full_like(f,fill_value=123)

array([[123, 123, 123],
       [123, 123, 123],
       [123, 123, 123],
       [123, 123, 123],
       [123, 123, 123],
       [123, 123, 123],
       [123, 123, 123],
       [123, 123, 123]])

In [100]:
n.empty((3,4,2),n.int8)

array([[[-128,   93],
        [  57,    3],
        [   0,    0],
        [   0,    0]],

       [[   0,    0],
        [   0,    0],
        [   0,    0],
        [   0,    0]],

       [[ -16,    0],
        [   0,    0],
        [   0,    0],
        [   0,    0]]], dtype=int8)

In [15]:
l=n.zeros((3,4,5),n.int8)
l[2,3,4]=10
l[1,3,4]=10
l[2,2,4]=11
l

array([[[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 10]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 11],
        [ 0,  0,  0,  0, 10]]], dtype=int8)

In [3]:
n.full((2,4,5),13)

array([[[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]],

       [[13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13],
        [13, 13, 13, 13, 13]]])

In [4]:
print(l.all(),l.shape,l.size,sep=" , ")

False , (3, 4, 5) , 60


In [17]:
l.argmax(0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 1]])

In [28]:
m=n.arange(10).reshape(2,5)
m.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [29]:
m.argmax(1)

array([4, 4])

In [30]:
m.argmax(0)

array([1, 1, 1, 1, 1])

In [31]:
m.argmin(1)

array([0, 0])

In [32]:
m.argmin(0)

array([0, 0, 0, 0, 0])

In [39]:
x=m.transpose()
x

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [41]:
x.argmax()# empty provide with the min in the matrix

9

In [42]:
x.argmax(1) # give the index of max element along column

array([1, 1, 1, 1, 1])

In [43]:
x.argmax(0) # give the index of max element along rows

array([4, 4])

In [44]:
x.argmin()# empty provide with the min in the matrix

0

In [21]:
v=n.array([[1,23],[4,3],[4,3]]) # it requires the same length of vector in each row if not given error!
n.argwhere(v>20)#Indices of elements that are less then great then equal to number "20 for example". Indices are grouped by element.

array([[0, 1]])

In [22]:
n.alen(v) # the arra outermost vector's dimension (how many element are there in it)

3